version: "3.8"

services:
  django_gunicorn:
    image: asaadna/api-project-app
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8001:8001"
  nginx:
    image: asaadna/api-project-nginx
    build: ./nginx
    volumes:
      - static:/static
    expose:
      - "80:80"
    depends_on:
      - django_gunicorn

volumes:
  static: